import Head from 'next/head';

export default function Home() {
  return (
    <div className="bg-slate-600 py-10">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-100 mx-auto"></main>
    </div>
  );
}
